// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.3
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xstream.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XStream_CfgInitialize(XStream *InstancePtr, XStream_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XStream_Set_l(XStream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStream_WriteReg(InstancePtr->Axilites_BaseAddress, XSTREAM_AXILITES_ADDR_L_DATA, Data);
}

u32 XStream_Get_l(XStream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStream_ReadReg(InstancePtr->Axilites_BaseAddress, XSTREAM_AXILITES_ADDR_L_DATA);
    return Data;
}

void XStream_Set_c(XStream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStream_WriteReg(InstancePtr->Axilites_BaseAddress, XSTREAM_AXILITES_ADDR_C_DATA, Data);
}

u32 XStream_Get_c(XStream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStream_ReadReg(InstancePtr->Axilites_BaseAddress, XSTREAM_AXILITES_ADDR_C_DATA);
    return Data;
}

void XStream_Set_r(XStream *InstancePtr, u32 Data) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XStream_WriteReg(InstancePtr->Axilites_BaseAddress, XSTREAM_AXILITES_ADDR_R_DATA, Data);
}

u32 XStream_Get_r(XStream *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XStream_ReadReg(InstancePtr->Axilites_BaseAddress, XSTREAM_AXILITES_ADDR_R_DATA);
    return Data;
}

