// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// ==============================================================

extern void AESL_WRAP_stream (
hls::stream<struct ap_axiu<32, 1, 1, 1 > > (&src),
hls::stream<struct ap_axiu<32, 1, 1, 1 > > (&dst),
unsigned char kernelchc,
unsigned char normalfactor,
unsigned char channelselector);
