// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of kernelchc
//        bit 7~0 - kernelchc[7:0] (Read/Write)
//        others  - reserved
// 0x14 : reserved
// 0x18 : Data signal of normalfactor
//        bit 7~0 - normalfactor[7:0] (Read/Write)
//        others  - reserved
// 0x1c : reserved
// 0x20 : Data signal of channelselector
//        bit 7~0 - channelselector[7:0] (Read/Write)
//        others  - reserved
// 0x24 : reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XSTREAM_AXILITES_ADDR_KERNELCHC_DATA       0x10
#define XSTREAM_AXILITES_BITS_KERNELCHC_DATA       8
#define XSTREAM_AXILITES_ADDR_NORMALFACTOR_DATA    0x18
#define XSTREAM_AXILITES_BITS_NORMALFACTOR_DATA    8
#define XSTREAM_AXILITES_ADDR_CHANNELSELECTOR_DATA 0x20
#define XSTREAM_AXILITES_BITS_CHANNELSELECTOR_DATA 8

